[project]
name = "celeste64"
version = "1.0.0"
description = "Relive the magic of Celeste Mountain alongside Madeline in this small, heartfelt 3D platformer. Created in a week(ish) by the Celeste team to celebrate the gameâ€™s sixth anniversary ðŸ“âœ¨"
authors = [
    {name = "PoryGone"}
]
requires-python = ">=3.12"

[project.entry-points."mwgg.plugins"]
"celeste64.WorldClass" = "celeste64.Register:WORLD_CLASS"
"celeste64.WebWorldClass" = "celeste64.Register:WEB_WORLD_CLASS"
"celeste64.Client" = "celeste64.Register:CLIENT_FUNCTION"
